/* This file was autogenerated by ctest; do not modify directly */
{#- ↑ Doesn't apply here, this is the template! +#}

{%- let ctx = self.template +%}

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

{%- for header in self.headers +%}
#include <{{ header }}>
{%- endfor +%}


{%- for item in ctx.c_str_tests +%}
static {{ item.c_ty }} ctest_const_{{ item.ident }}_val_static = {{ item.c_ident }};

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
{{ item.c_ty }}* ctest_const_{{ item.ident }}_val(void) {
    return &ctest_const_{{ item.ident }}_val_static;
}
{%- endfor +%}


{%- for item in ctx.const_tests +%}
static {{ item.c_ty }} ctest_const_{{ item.ident }}_val_static = {{ item.c_ident }};

// Define a function that returns a pointer to the value of the constant to test.
// This will later be called on the Rust side via FFI.
{{ item.c_ty }}* ctest_const_{{ item.ident }}_val(void) {
    return &ctest_const_{{ item.ident }}_val_static;
}
{%- endfor +%}


{%- for item in ffi_items.size_align_tests +%}
/// Return the size of a type.
uint64_t ctest_size_of__{{ item.ident }}(void) { return sizeof({{ item.c_ty }}); }

/// Return the alignment of a type.
uint64_t ctest_align_of__{{ item.ident }}(void) { return _Alignof({{ item.c_ty }}); }
{%- endfor +%}
